# Config settings
title: Git Wiki
baseurl: "/lyonsn1/git-wiki"
permalink: pretty

tipue_search:
  include:
    pages: true
  exclude:
    files: []

# Build settings
markdown: kramdown

sass:
  sass_dir: ./css
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - /css/vendor
  - /js/tipuesearch_content.js
  - Rakefile
